// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: loan-fine/loan-fine.proto

package fine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define the LoanFine message
type LoanFine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LoanId        string                 `protobuf:"bytes,2,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	FineAmount    float32                `protobuf:"fixed32,3,opt,name=fine_amount,json=fineAmount,proto3" json:"fine_amount,omitempty"`
	Paid          bool                   `protobuf:"varint,4,opt,name=paid,proto3" json:"paid,omitempty"`
	PaidAt        string                 `protobuf:"bytes,5,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"` // ISO 8601, nullable if not paid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanFine) Reset() {
	*x = LoanFine{}
	mi := &file_loan_fine_loan_fine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanFine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanFine) ProtoMessage() {}

func (x *LoanFine) ProtoReflect() protoreflect.Message {
	mi := &file_loan_fine_loan_fine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanFine.ProtoReflect.Descriptor instead.
func (*LoanFine) Descriptor() ([]byte, []int) {
	return file_loan_fine_loan_fine_proto_rawDescGZIP(), []int{0}
}

func (x *LoanFine) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoanFine) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

func (x *LoanFine) GetFineAmount() float32 {
	if x != nil {
		return x.FineAmount
	}
	return 0
}

func (x *LoanFine) GetPaid() bool {
	if x != nil {
		return x.Paid
	}
	return false
}

func (x *LoanFine) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

// Request to create a fine
type CreateFineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fine          *LoanFine              `protobuf:"bytes,1,opt,name=fine,proto3" json:"fine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFineRequest) Reset() {
	*x = CreateFineRequest{}
	mi := &file_loan_fine_loan_fine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFineRequest) ProtoMessage() {}

func (x *CreateFineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_fine_loan_fine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFineRequest.ProtoReflect.Descriptor instead.
func (*CreateFineRequest) Descriptor() ([]byte, []int) {
	return file_loan_fine_loan_fine_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFineRequest) GetFine() *LoanFine {
	if x != nil {
		return x.Fine
	}
	return nil
}

// Response when a fine is created
type CreateFineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFineResponse) Reset() {
	*x = CreateFineResponse{}
	mi := &file_loan_fine_loan_fine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFineResponse) ProtoMessage() {}

func (x *CreateFineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_fine_loan_fine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFineResponse.ProtoReflect.Descriptor instead.
func (*CreateFineResponse) Descriptor() ([]byte, []int) {
	return file_loan_fine_loan_fine_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFineResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request to update a fine
type UpdateFineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fine          *LoanFine              `protobuf:"bytes,1,opt,name=fine,proto3" json:"fine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFineRequest) Reset() {
	*x = UpdateFineRequest{}
	mi := &file_loan_fine_loan_fine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFineRequest) ProtoMessage() {}

func (x *UpdateFineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_fine_loan_fine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFineRequest.ProtoReflect.Descriptor instead.
func (*UpdateFineRequest) Descriptor() ([]byte, []int) {
	return file_loan_fine_loan_fine_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateFineRequest) GetFine() *LoanFine {
	if x != nil {
		return x.Fine
	}
	return nil
}

// Response when a fine is updated
type UpdateFineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFineResponse) Reset() {
	*x = UpdateFineResponse{}
	mi := &file_loan_fine_loan_fine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFineResponse) ProtoMessage() {}

func (x *UpdateFineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_fine_loan_fine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFineResponse.ProtoReflect.Descriptor instead.
func (*UpdateFineResponse) Descriptor() ([]byte, []int) {
	return file_loan_fine_loan_fine_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateFineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request for listing fines with search, sort, and pagination
type ListFinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchQuery   string                 `protobuf:"bytes,1,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"` // Search query to filter by loan_id, fine_amount, etc.
	SortBy        string                 `protobuf:"bytes,2,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`                // Field to sort by (e.g., fine_amount, paid_at, etc.)
	SortOrder     string                 `protobuf:"bytes,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`       // Sort order (asc or desc)
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`                                 // Page number (for pagination)
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`         // Number of items per page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFinesRequest) Reset() {
	*x = ListFinesRequest{}
	mi := &file_loan_fine_loan_fine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFinesRequest) ProtoMessage() {}

func (x *ListFinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_fine_loan_fine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFinesRequest.ProtoReflect.Descriptor instead.
func (*ListFinesRequest) Descriptor() ([]byte, []int) {
	return file_loan_fine_loan_fine_proto_rawDescGZIP(), []int{5}
}

func (x *ListFinesRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *ListFinesRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListFinesRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *ListFinesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFinesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Response when listing fines with pagination
type ListFinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fines         []*LoanFine            `protobuf:"bytes,1,rep,name=fines,proto3" json:"fines,omitempty"`                              // List of fines returned
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Total number of fines that match the query
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFinesResponse) Reset() {
	*x = ListFinesResponse{}
	mi := &file_loan_fine_loan_fine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFinesResponse) ProtoMessage() {}

func (x *ListFinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_fine_loan_fine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFinesResponse.ProtoReflect.Descriptor instead.
func (*ListFinesResponse) Descriptor() ([]byte, []int) {
	return file_loan_fine_loan_fine_proto_rawDescGZIP(), []int{6}
}

func (x *ListFinesResponse) GetFines() []*LoanFine {
	if x != nil {
		return x.Fines
	}
	return nil
}

func (x *ListFinesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_loan_fine_loan_fine_proto protoreflect.FileDescriptor

const file_loan_fine_loan_fine_proto_rawDesc = "" +
	"\n" +
	"\x19loan-fine/loan-fine.proto\x12\x04fine\"\x81\x01\n" +
	"\bLoanFine\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aloan_id\x18\x02 \x01(\tR\x06loanId\x12\x1f\n" +
	"\vfine_amount\x18\x03 \x01(\x02R\n" +
	"fineAmount\x12\x12\n" +
	"\x04paid\x18\x04 \x01(\bR\x04paid\x12\x17\n" +
	"\apaid_at\x18\x05 \x01(\tR\x06paidAt\"7\n" +
	"\x11CreateFineRequest\x12\"\n" +
	"\x04fine\x18\x01 \x01(\v2\x0e.fine.LoanFineR\x04fine\"$\n" +
	"\x12CreateFineResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x11UpdateFineRequest\x12\"\n" +
	"\x04fine\x18\x01 \x01(\v2\x0e.fine.LoanFineR\x04fine\".\n" +
	"\x12UpdateFineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9e\x01\n" +
	"\x10ListFinesRequest\x12!\n" +
	"\fsearch_query\x18\x01 \x01(\tR\vsearchQuery\x12\x17\n" +
	"\asort_by\x18\x02 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\tR\tsortOrder\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"Z\n" +
	"\x11ListFinesResponse\x12$\n" +
	"\x05fines\x18\x01 \x03(\v2\x0e.fine.LoanFineR\x05fines\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount2\xcd\x01\n" +
	"\vFineService\x12?\n" +
	"\n" +
	"CreateFine\x12\x17.fine.CreateFineRequest\x1a\x18.fine.CreateFineResponse\x12?\n" +
	"\n" +
	"UpdateFine\x12\x17.fine.UpdateFineRequest\x1a\x18.fine.UpdateFineResponse\x12<\n" +
	"\tListFines\x12\x16.fine.ListFinesRequest\x1a\x17.fine.ListFinesResponseB\tZ\a./;fineb\x06proto3"

var (
	file_loan_fine_loan_fine_proto_rawDescOnce sync.Once
	file_loan_fine_loan_fine_proto_rawDescData []byte
)

func file_loan_fine_loan_fine_proto_rawDescGZIP() []byte {
	file_loan_fine_loan_fine_proto_rawDescOnce.Do(func() {
		file_loan_fine_loan_fine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loan_fine_loan_fine_proto_rawDesc), len(file_loan_fine_loan_fine_proto_rawDesc)))
	})
	return file_loan_fine_loan_fine_proto_rawDescData
}

var file_loan_fine_loan_fine_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_loan_fine_loan_fine_proto_goTypes = []any{
	(*LoanFine)(nil),           // 0: fine.LoanFine
	(*CreateFineRequest)(nil),  // 1: fine.CreateFineRequest
	(*CreateFineResponse)(nil), // 2: fine.CreateFineResponse
	(*UpdateFineRequest)(nil),  // 3: fine.UpdateFineRequest
	(*UpdateFineResponse)(nil), // 4: fine.UpdateFineResponse
	(*ListFinesRequest)(nil),   // 5: fine.ListFinesRequest
	(*ListFinesResponse)(nil),  // 6: fine.ListFinesResponse
}
var file_loan_fine_loan_fine_proto_depIdxs = []int32{
	0, // 0: fine.CreateFineRequest.fine:type_name -> fine.LoanFine
	0, // 1: fine.UpdateFineRequest.fine:type_name -> fine.LoanFine
	0, // 2: fine.ListFinesResponse.fines:type_name -> fine.LoanFine
	1, // 3: fine.FineService.CreateFine:input_type -> fine.CreateFineRequest
	3, // 4: fine.FineService.UpdateFine:input_type -> fine.UpdateFineRequest
	5, // 5: fine.FineService.ListFines:input_type -> fine.ListFinesRequest
	2, // 6: fine.FineService.CreateFine:output_type -> fine.CreateFineResponse
	4, // 7: fine.FineService.UpdateFine:output_type -> fine.UpdateFineResponse
	6, // 8: fine.FineService.ListFines:output_type -> fine.ListFinesResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_loan_fine_loan_fine_proto_init() }
func file_loan_fine_loan_fine_proto_init() {
	if File_loan_fine_loan_fine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loan_fine_loan_fine_proto_rawDesc), len(file_loan_fine_loan_fine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loan_fine_loan_fine_proto_goTypes,
		DependencyIndexes: file_loan_fine_loan_fine_proto_depIdxs,
		MessageInfos:      file_loan_fine_loan_fine_proto_msgTypes,
	}.Build()
	File_loan_fine_loan_fine_proto = out.File
	file_loan_fine_loan_fine_proto_goTypes = nil
	file_loan_fine_loan_fine_proto_depIdxs = nil
}
