// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: member/member.proto

package member

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   int64                  `protobuf:"varint,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	RegisteredAt  string                 `protobuf:"bytes,6,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"` // ISO 8601 datetime string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_member_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{0}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Member) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Member) GetPhoneNumber() int64 {
	if x != nil {
		return x.PhoneNumber
	}
	return 0
}

func (x *Member) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Member) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

type CreateMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemberRequest) Reset() {
	*x = CreateMemberRequest{}
	mi := &file_member_member_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemberRequest) ProtoMessage() {}

func (x *CreateMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemberRequest.ProtoReflect.Descriptor instead.
func (*CreateMemberRequest) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMemberRequest) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type CreateMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemberResponse) Reset() {
	*x = CreateMemberResponse{}
	mi := &file_member_member_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemberResponse) ProtoMessage() {}

func (x *CreateMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemberResponse.ProtoReflect.Descriptor instead.
func (*CreateMemberResponse) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMemberResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMemberRequest) Reset() {
	*x = ReadMemberRequest{}
	mi := &file_member_member_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMemberRequest) ProtoMessage() {}

func (x *ReadMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMemberRequest.ProtoReflect.Descriptor instead.
func (*ReadMemberRequest) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{3}
}

func (x *ReadMemberRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMemberResponse) Reset() {
	*x = ReadMemberResponse{}
	mi := &file_member_member_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMemberResponse) ProtoMessage() {}

func (x *ReadMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMemberResponse.ProtoReflect.Descriptor instead.
func (*ReadMemberResponse) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{4}
}

func (x *ReadMemberResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type UpdateMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRequest) Reset() {
	*x = UpdateMemberRequest{}
	mi := &file_member_member_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRequest) ProtoMessage() {}

func (x *UpdateMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberRequest) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMemberRequest) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type UpdateMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberResponse) Reset() {
	*x = UpdateMemberResponse{}
	mi := &file_member_member_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberResponse) ProtoMessage() {}

func (x *UpdateMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberResponse.ProtoReflect.Descriptor instead.
func (*UpdateMemberResponse) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMemberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemberRequest) Reset() {
	*x = DeleteMemberRequest{}
	mi := &file_member_member_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemberRequest) ProtoMessage() {}

func (x *DeleteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemberRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemberRequest) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMemberRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemberResponse) Reset() {
	*x = DeleteMemberResponse{}
	mi := &file_member_member_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemberResponse) ProtoMessage() {}

func (x *DeleteMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemberResponse.ProtoReflect.Descriptor instead.
func (*DeleteMemberResponse) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMemberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_member_member_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{9}
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_member_member_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{10}
}

func (x *ListMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_member_member_proto protoreflect.FileDescriptor

const file_member_member_proto_rawDesc = "" +
	"\n" +
	"\x13member/member.proto\x12\x06member\"\xa4\x01\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x04 \x01(\x03R\vphoneNumber\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12#\n" +
	"\rregistered_at\x18\x06 \x01(\tR\fregisteredAt\"=\n" +
	"\x13CreateMemberRequest\x12&\n" +
	"\x06member\x18\x01 \x01(\v2\x0e.member.MemberR\x06member\"&\n" +
	"\x14CreateMemberResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11ReadMemberRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x12ReadMemberResponse\x12&\n" +
	"\x06member\x18\x01 \x01(\v2\x0e.member.MemberR\x06member\"=\n" +
	"\x13UpdateMemberRequest\x12&\n" +
	"\x06member\x18\x01 \x01(\v2\x0e.member.MemberR\x06member\"0\n" +
	"\x14UpdateMemberResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"%\n" +
	"\x13DeleteMemberRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeleteMemberResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x14\n" +
	"\x12ListMembersRequest\"?\n" +
	"\x13ListMembersResponse\x12(\n" +
	"\amembers\x18\x01 \x03(\v2\x0e.member.MemberR\amembers2\xfd\x02\n" +
	"\rMemberService\x12I\n" +
	"\fCreateMember\x12\x1b.member.CreateMemberRequest\x1a\x1c.member.CreateMemberResponse\x12C\n" +
	"\n" +
	"ReadMember\x12\x19.member.ReadMemberRequest\x1a\x1a.member.ReadMemberResponse\x12I\n" +
	"\fUpdateMember\x12\x1b.member.UpdateMemberRequest\x1a\x1c.member.UpdateMemberResponse\x12I\n" +
	"\fDeleteMember\x12\x1b.member.DeleteMemberRequest\x1a\x1c.member.DeleteMemberResponse\x12F\n" +
	"\vListMembers\x12\x1a.member.ListMembersRequest\x1a\x1b.member.ListMembersResponseB\vZ\t./;memberb\x06proto3"

var (
	file_member_member_proto_rawDescOnce sync.Once
	file_member_member_proto_rawDescData []byte
)

func file_member_member_proto_rawDescGZIP() []byte {
	file_member_member_proto_rawDescOnce.Do(func() {
		file_member_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_member_member_proto_rawDesc), len(file_member_member_proto_rawDesc)))
	})
	return file_member_member_proto_rawDescData
}

var file_member_member_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_member_member_proto_goTypes = []any{
	(*Member)(nil),               // 0: member.Member
	(*CreateMemberRequest)(nil),  // 1: member.CreateMemberRequest
	(*CreateMemberResponse)(nil), // 2: member.CreateMemberResponse
	(*ReadMemberRequest)(nil),    // 3: member.ReadMemberRequest
	(*ReadMemberResponse)(nil),   // 4: member.ReadMemberResponse
	(*UpdateMemberRequest)(nil),  // 5: member.UpdateMemberRequest
	(*UpdateMemberResponse)(nil), // 6: member.UpdateMemberResponse
	(*DeleteMemberRequest)(nil),  // 7: member.DeleteMemberRequest
	(*DeleteMemberResponse)(nil), // 8: member.DeleteMemberResponse
	(*ListMembersRequest)(nil),   // 9: member.ListMembersRequest
	(*ListMembersResponse)(nil),  // 10: member.ListMembersResponse
}
var file_member_member_proto_depIdxs = []int32{
	0,  // 0: member.CreateMemberRequest.member:type_name -> member.Member
	0,  // 1: member.ReadMemberResponse.member:type_name -> member.Member
	0,  // 2: member.UpdateMemberRequest.member:type_name -> member.Member
	0,  // 3: member.ListMembersResponse.members:type_name -> member.Member
	1,  // 4: member.MemberService.CreateMember:input_type -> member.CreateMemberRequest
	3,  // 5: member.MemberService.ReadMember:input_type -> member.ReadMemberRequest
	5,  // 6: member.MemberService.UpdateMember:input_type -> member.UpdateMemberRequest
	7,  // 7: member.MemberService.DeleteMember:input_type -> member.DeleteMemberRequest
	9,  // 8: member.MemberService.ListMembers:input_type -> member.ListMembersRequest
	2,  // 9: member.MemberService.CreateMember:output_type -> member.CreateMemberResponse
	4,  // 10: member.MemberService.ReadMember:output_type -> member.ReadMemberResponse
	6,  // 11: member.MemberService.UpdateMember:output_type -> member.UpdateMemberResponse
	8,  // 12: member.MemberService.DeleteMember:output_type -> member.DeleteMemberResponse
	10, // 13: member.MemberService.ListMembers:output_type -> member.ListMembersResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_member_member_proto_init() }
func file_member_member_proto_init() {
	if File_member_member_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_member_member_proto_rawDesc), len(file_member_member_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_member_member_proto_goTypes,
		DependencyIndexes: file_member_member_proto_depIdxs,
		MessageInfos:      file_member_member_proto_msgTypes,
	}.Build()
	File_member_member_proto = out.File
	file_member_member_proto_goTypes = nil
	file_member_member_proto_depIdxs = nil
}
