FROM golang:1.24.5-alpine AS builder

WORKDIR /go/src/app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags="-s -w" -o grpc-server ./main.go

FROM scratch

COPY --from=builder /go/src/app/grpc-server /grpc-server

EXPOSE 50052

ENTRYPOINT ["/grpc-server"]
