// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: book/book.proto

package book

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define a Book message
type Book struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author            string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Publisher         string                 `protobuf:"bytes,4,opt,name=publisher,proto3" json:"publisher,omitempty"`
	Year              int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Isbn              string                 `protobuf:"bytes,6,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Quantity          int32                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	AvailableQuantity int32                  `protobuf:"varint,8,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_book_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *Book) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Book) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *Book) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Book) GetAvailableQuantity() int32 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

// Request to create a book
type CreateBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Book                  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookRequest) Reset() {
	*x = CreateBookRequest{}
	mi := &file_book_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookRequest) ProtoMessage() {}

func (x *CreateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookRequest.ProtoReflect.Descriptor instead.
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBookRequest) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

// Response when a book is created
type CreateBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookResponse) Reset() {
	*x = CreateBookResponse{}
	mi := &file_book_book_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookResponse) ProtoMessage() {}

func (x *CreateBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookResponse.ProtoReflect.Descriptor instead.
func (*CreateBookResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBookResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Request to read a specific book by ID
type ReadBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadBookRequest) Reset() {
	*x = ReadBookRequest{}
	mi := &file_book_book_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBookRequest) ProtoMessage() {}

func (x *ReadBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBookRequest.ProtoReflect.Descriptor instead.
func (*ReadBookRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{3}
}

func (x *ReadBookRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Response for reading a specific book
type ReadBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Book                  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadBookResponse) Reset() {
	*x = ReadBookResponse{}
	mi := &file_book_book_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBookResponse) ProtoMessage() {}

func (x *ReadBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBookResponse.ProtoReflect.Descriptor instead.
func (*ReadBookResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{4}
}

func (x *ReadBookResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

// Request to update a book
type UpdateBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Book                  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookRequest) Reset() {
	*x = UpdateBookRequest{}
	mi := &file_book_book_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookRequest) ProtoMessage() {}

func (x *UpdateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBookRequest) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

// Response when a book is updated
type UpdateBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookResponse) Reset() {
	*x = UpdateBookResponse{}
	mi := &file_book_book_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookResponse) ProtoMessage() {}

func (x *UpdateBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookResponse.ProtoReflect.Descriptor instead.
func (*UpdateBookResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request to delete a book
type DeleteBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookRequest) Reset() {
	*x = DeleteBookRequest{}
	mi := &file_book_book_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookRequest) ProtoMessage() {}

func (x *DeleteBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBookRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Response when a book is deleted
type DeleteBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookResponse) Reset() {
	*x = DeleteBookResponse{}
	mi := &file_book_book_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookResponse) ProtoMessage() {}

func (x *DeleteBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookResponse.ProtoReflect.Descriptor instead.
func (*DeleteBookResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteBookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request for listing books with search, sort, and pagination
type ListBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*Filter              `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`                      // List of filters with column name and value
	SortBy        string                 `protobuf:"bytes,2,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`          // Field to sort by (e.g., title, year, etc.)
	SortOrder     string                 `protobuf:"bytes,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // Sort order (asc or desc)
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`                           // Page number (for pagination)
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // Number of items per page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksRequest) Reset() {
	*x = ListBooksRequest{}
	mi := &file_book_book_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksRequest) ProtoMessage() {}

func (x *ListBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksRequest.ProtoReflect.Descriptor instead.
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{9}
}

func (x *ListBooksRequest) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ListBooksRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListBooksRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *ListBooksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBooksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Define the Filter message to specify column name and value
type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchBy      string                 `protobuf:"bytes,1,opt,name=search_by,json=searchBy,proto3" json:"search_by,omitempty"` // The column name to filter by (e.g., title, author)
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`                       // The value to match in the column
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_book_book_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{10}
}

func (x *Filter) GetSearchBy() string {
	if x != nil {
		return x.SearchBy
	}
	return ""
}

func (x *Filter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Response for listing books with pagination
type ListBooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*Book                `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`                                 // List of books returned
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`    // Total number of books matching the query
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"` // Current page number
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`    // Total number of pages based on total_count and page_size
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`          // Number of books per page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksResponse) Reset() {
	*x = ListBooksResponse{}
	mi := &file_book_book_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksResponse) ProtoMessage() {}

func (x *ListBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksResponse.ProtoReflect.Descriptor instead.
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{11}
}

func (x *ListBooksResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

func (x *ListBooksResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListBooksResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ListBooksResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *ListBooksResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_book_book_proto protoreflect.FileDescriptor

const file_book_book_proto_rawDesc = "" +
	"\n" +
	"\x0fbook/book.proto\x12\x04book\"\xd5\x01\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x1c\n" +
	"\tpublisher\x18\x04 \x01(\tR\tpublisher\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12\x12\n" +
	"\x04isbn\x18\x06 \x01(\tR\x04isbn\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x05R\bquantity\x12-\n" +
	"\x12available_quantity\x18\b \x01(\x05R\x11availableQuantity\"3\n" +
	"\x11CreateBookRequest\x12\x1e\n" +
	"\x04book\x18\x01 \x01(\v2\n" +
	".book.BookR\x04book\"$\n" +
	"\x12CreateBookResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"!\n" +
	"\x0fReadBookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"2\n" +
	"\x10ReadBookResponse\x12\x1e\n" +
	"\x04book\x18\x01 \x01(\v2\n" +
	".book.BookR\x04book\"3\n" +
	"\x11UpdateBookRequest\x12\x1e\n" +
	"\x04book\x18\x01 \x01(\v2\n" +
	".book.BookR\x04book\".\n" +
	"\x12UpdateBookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"\x11DeleteBookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\".\n" +
	"\x12DeleteBookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa3\x01\n" +
	"\x10ListBooksRequest\x12&\n" +
	"\afilters\x18\x01 \x03(\v2\f.book.FilterR\afilters\x12\x17\n" +
	"\asort_by\x18\x02 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\tR\tsortOrder\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\";\n" +
	"\x06Filter\x12\x1b\n" +
	"\tsearch_by\x18\x01 \x01(\tR\bsearchBy\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xb7\x01\n" +
	"\x11ListBooksResponse\x12 \n" +
	"\x05books\x18\x01 \x03(\v2\n" +
	".book.BookR\x05books\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize2\xc9\x02\n" +
	"\vBookService\x12?\n" +
	"\n" +
	"CreateBook\x12\x17.book.CreateBookRequest\x1a\x18.book.CreateBookResponse\x129\n" +
	"\bReadBook\x12\x15.book.ReadBookRequest\x1a\x16.book.ReadBookResponse\x12?\n" +
	"\n" +
	"UpdateBook\x12\x17.book.UpdateBookRequest\x1a\x18.book.UpdateBookResponse\x12?\n" +
	"\n" +
	"DeleteBook\x12\x17.book.DeleteBookRequest\x1a\x18.book.DeleteBookResponse\x12<\n" +
	"\tListBooks\x12\x16.book.ListBooksRequest\x1a\x17.book.ListBooksResponseB\rZ\v./book;bookb\x06proto3"

var (
	file_book_book_proto_rawDescOnce sync.Once
	file_book_book_proto_rawDescData []byte
)

func file_book_book_proto_rawDescGZIP() []byte {
	file_book_book_proto_rawDescOnce.Do(func() {
		file_book_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_book_book_proto_rawDesc), len(file_book_book_proto_rawDesc)))
	})
	return file_book_book_proto_rawDescData
}

var file_book_book_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_book_book_proto_goTypes = []any{
	(*Book)(nil),               // 0: book.Book
	(*CreateBookRequest)(nil),  // 1: book.CreateBookRequest
	(*CreateBookResponse)(nil), // 2: book.CreateBookResponse
	(*ReadBookRequest)(nil),    // 3: book.ReadBookRequest
	(*ReadBookResponse)(nil),   // 4: book.ReadBookResponse
	(*UpdateBookRequest)(nil),  // 5: book.UpdateBookRequest
	(*UpdateBookResponse)(nil), // 6: book.UpdateBookResponse
	(*DeleteBookRequest)(nil),  // 7: book.DeleteBookRequest
	(*DeleteBookResponse)(nil), // 8: book.DeleteBookResponse
	(*ListBooksRequest)(nil),   // 9: book.ListBooksRequest
	(*Filter)(nil),             // 10: book.Filter
	(*ListBooksResponse)(nil),  // 11: book.ListBooksResponse
}
var file_book_book_proto_depIdxs = []int32{
	0,  // 0: book.CreateBookRequest.book:type_name -> book.Book
	0,  // 1: book.ReadBookResponse.book:type_name -> book.Book
	0,  // 2: book.UpdateBookRequest.book:type_name -> book.Book
	10, // 3: book.ListBooksRequest.filters:type_name -> book.Filter
	0,  // 4: book.ListBooksResponse.books:type_name -> book.Book
	1,  // 5: book.BookService.CreateBook:input_type -> book.CreateBookRequest
	3,  // 6: book.BookService.ReadBook:input_type -> book.ReadBookRequest
	5,  // 7: book.BookService.UpdateBook:input_type -> book.UpdateBookRequest
	7,  // 8: book.BookService.DeleteBook:input_type -> book.DeleteBookRequest
	9,  // 9: book.BookService.ListBooks:input_type -> book.ListBooksRequest
	2,  // 10: book.BookService.CreateBook:output_type -> book.CreateBookResponse
	4,  // 11: book.BookService.ReadBook:output_type -> book.ReadBookResponse
	6,  // 12: book.BookService.UpdateBook:output_type -> book.UpdateBookResponse
	8,  // 13: book.BookService.DeleteBook:output_type -> book.DeleteBookResponse
	11, // 14: book.BookService.ListBooks:output_type -> book.ListBooksResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_book_book_proto_init() }
func file_book_book_proto_init() {
	if File_book_book_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_book_proto_rawDesc), len(file_book_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_book_book_proto_goTypes,
		DependencyIndexes: file_book_book_proto_depIdxs,
		MessageInfos:      file_book_book_proto_msgTypes,
	}.Build()
	File_book_book_proto = out.File
	file_book_book_proto_goTypes = nil
	file_book_book_proto_depIdxs = nil
}
