// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: loan/loan.proto

package loan

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoanService_CreateLoan_FullMethodName = "/loan.LoanService/CreateLoan"
	LoanService_ReadLoan_FullMethodName   = "/loan.LoanService/ReadLoan"
	LoanService_UpdateLoan_FullMethodName = "/loan.LoanService/UpdateLoan"
	LoanService_DeleteLoan_FullMethodName = "/loan.LoanService/DeleteLoan"
	LoanService_ListLoans_FullMethodName  = "/loan.LoanService/ListLoans"
)

// LoanServiceClient is the client API for LoanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Loan service with CRUD operations
type LoanServiceClient interface {
	CreateLoan(ctx context.Context, in *CreateLoanRequest, opts ...grpc.CallOption) (*CreateLoanResponse, error)
	ReadLoan(ctx context.Context, in *ReadLoanRequest, opts ...grpc.CallOption) (*ReadLoanResponse, error)
	UpdateLoan(ctx context.Context, in *UpdateLoanRequest, opts ...grpc.CallOption) (*UpdateLoanResponse, error)
	DeleteLoan(ctx context.Context, in *DeleteLoanRequest, opts ...grpc.CallOption) (*DeleteLoanResponse, error)
	ListLoans(ctx context.Context, in *ListLoansRequest, opts ...grpc.CallOption) (*ListLoansResponse, error)
}

type loanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoanServiceClient(cc grpc.ClientConnInterface) LoanServiceClient {
	return &loanServiceClient{cc}
}

func (c *loanServiceClient) CreateLoan(ctx context.Context, in *CreateLoanRequest, opts ...grpc.CallOption) (*CreateLoanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLoanResponse)
	err := c.cc.Invoke(ctx, LoanService_CreateLoan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) ReadLoan(ctx context.Context, in *ReadLoanRequest, opts ...grpc.CallOption) (*ReadLoanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadLoanResponse)
	err := c.cc.Invoke(ctx, LoanService_ReadLoan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) UpdateLoan(ctx context.Context, in *UpdateLoanRequest, opts ...grpc.CallOption) (*UpdateLoanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLoanResponse)
	err := c.cc.Invoke(ctx, LoanService_UpdateLoan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) DeleteLoan(ctx context.Context, in *DeleteLoanRequest, opts ...grpc.CallOption) (*DeleteLoanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLoanResponse)
	err := c.cc.Invoke(ctx, LoanService_DeleteLoan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) ListLoans(ctx context.Context, in *ListLoansRequest, opts ...grpc.CallOption) (*ListLoansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLoansResponse)
	err := c.cc.Invoke(ctx, LoanService_ListLoans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoanServiceServer is the server API for LoanService service.
// All implementations must embed UnimplementedLoanServiceServer
// for forward compatibility.
//
// Loan service with CRUD operations
type LoanServiceServer interface {
	CreateLoan(context.Context, *CreateLoanRequest) (*CreateLoanResponse, error)
	ReadLoan(context.Context, *ReadLoanRequest) (*ReadLoanResponse, error)
	UpdateLoan(context.Context, *UpdateLoanRequest) (*UpdateLoanResponse, error)
	DeleteLoan(context.Context, *DeleteLoanRequest) (*DeleteLoanResponse, error)
	ListLoans(context.Context, *ListLoansRequest) (*ListLoansResponse, error)
	mustEmbedUnimplementedLoanServiceServer()
}

// UnimplementedLoanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoanServiceServer struct{}

func (UnimplementedLoanServiceServer) CreateLoan(context.Context, *CreateLoanRequest) (*CreateLoanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLoan not implemented")
}
func (UnimplementedLoanServiceServer) ReadLoan(context.Context, *ReadLoanRequest) (*ReadLoanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadLoan not implemented")
}
func (UnimplementedLoanServiceServer) UpdateLoan(context.Context, *UpdateLoanRequest) (*UpdateLoanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLoan not implemented")
}
func (UnimplementedLoanServiceServer) DeleteLoan(context.Context, *DeleteLoanRequest) (*DeleteLoanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLoan not implemented")
}
func (UnimplementedLoanServiceServer) ListLoans(context.Context, *ListLoansRequest) (*ListLoansResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLoans not implemented")
}
func (UnimplementedLoanServiceServer) mustEmbedUnimplementedLoanServiceServer() {}
func (UnimplementedLoanServiceServer) testEmbeddedByValue()                     {}

// UnsafeLoanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoanServiceServer will
// result in compilation errors.
type UnsafeLoanServiceServer interface {
	mustEmbedUnimplementedLoanServiceServer()
}

func RegisterLoanServiceServer(s grpc.ServiceRegistrar, srv LoanServiceServer) {
	// If the following call pancis, it indicates UnimplementedLoanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoanService_ServiceDesc, srv)
}

func _LoanService_CreateLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).CreateLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_CreateLoan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).CreateLoan(ctx, req.(*CreateLoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_ReadLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadLoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).ReadLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_ReadLoan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).ReadLoan(ctx, req.(*ReadLoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_UpdateLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).UpdateLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_UpdateLoan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).UpdateLoan(ctx, req.(*UpdateLoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_DeleteLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).DeleteLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_DeleteLoan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).DeleteLoan(ctx, req.(*DeleteLoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_ListLoans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLoansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).ListLoans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_ListLoans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).ListLoans(ctx, req.(*ListLoansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoanService_ServiceDesc is the grpc.ServiceDesc for LoanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loan.LoanService",
	HandlerType: (*LoanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLoan",
			Handler:    _LoanService_CreateLoan_Handler,
		},
		{
			MethodName: "ReadLoan",
			Handler:    _LoanService_ReadLoan_Handler,
		},
		{
			MethodName: "UpdateLoan",
			Handler:    _LoanService_UpdateLoan_Handler,
		},
		{
			MethodName: "DeleteLoan",
			Handler:    _LoanService_DeleteLoan_Handler,
		},
		{
			MethodName: "ListLoans",
			Handler:    _LoanService_ListLoans_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loan/loan.proto",
}
