// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: loan/loan.proto

package loan

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define the Loan message
type Loan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	MemberId      string                 `protobuf:"bytes,3,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	LoanDate      string                 `protobuf:"bytes,4,opt,name=loan_date,json=loanDate,proto3" json:"loan_date,omitempty"`       // ISO 8601 string
	DueDate       string                 `protobuf:"bytes,5,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`          // ISO 8601 string
	ReturnDate    string                 `protobuf:"bytes,6,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"` // Nullable, ISO 8601 string
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                           // Example: "borrowed", "returned", "late"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Loan) Reset() {
	*x = Loan{}
	mi := &file_loan_loan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Loan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Loan) ProtoMessage() {}

func (x *Loan) ProtoReflect() protoreflect.Message {
	mi := &file_loan_loan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Loan.ProtoReflect.Descriptor instead.
func (*Loan) Descriptor() ([]byte, []int) {
	return file_loan_loan_proto_rawDescGZIP(), []int{0}
}

func (x *Loan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Loan) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *Loan) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *Loan) GetLoanDate() string {
	if x != nil {
		return x.LoanDate
	}
	return ""
}

func (x *Loan) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *Loan) GetReturnDate() string {
	if x != nil {
		return x.ReturnDate
	}
	return ""
}

func (x *Loan) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Request to create a loan
type CreateLoanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loan          *Loan                  `protobuf:"bytes,1,opt,name=loan,proto3" json:"loan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLoanRequest) Reset() {
	*x = CreateLoanRequest{}
	mi := &file_loan_loan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoanRequest) ProtoMessage() {}

func (x *CreateLoanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_loan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoanRequest.ProtoReflect.Descriptor instead.
func (*CreateLoanRequest) Descriptor() ([]byte, []int) {
	return file_loan_loan_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLoanRequest) GetLoan() *Loan {
	if x != nil {
		return x.Loan
	}
	return nil
}

// Response when a loan is created
type CreateLoanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLoanResponse) Reset() {
	*x = CreateLoanResponse{}
	mi := &file_loan_loan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoanResponse) ProtoMessage() {}

func (x *CreateLoanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_loan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoanResponse.ProtoReflect.Descriptor instead.
func (*CreateLoanResponse) Descriptor() ([]byte, []int) {
	return file_loan_loan_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLoanResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request to read a specific loan by ID
type ReadLoanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadLoanRequest) Reset() {
	*x = ReadLoanRequest{}
	mi := &file_loan_loan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLoanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLoanRequest) ProtoMessage() {}

func (x *ReadLoanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_loan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLoanRequest.ProtoReflect.Descriptor instead.
func (*ReadLoanRequest) Descriptor() ([]byte, []int) {
	return file_loan_loan_proto_rawDescGZIP(), []int{3}
}

func (x *ReadLoanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response for reading a specific loan
type ReadLoanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loan          *Loan                  `protobuf:"bytes,1,opt,name=loan,proto3" json:"loan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadLoanResponse) Reset() {
	*x = ReadLoanResponse{}
	mi := &file_loan_loan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLoanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLoanResponse) ProtoMessage() {}

func (x *ReadLoanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_loan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLoanResponse.ProtoReflect.Descriptor instead.
func (*ReadLoanResponse) Descriptor() ([]byte, []int) {
	return file_loan_loan_proto_rawDescGZIP(), []int{4}
}

func (x *ReadLoanResponse) GetLoan() *Loan {
	if x != nil {
		return x.Loan
	}
	return nil
}

// Request to update a loan
type UpdateLoanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loan          *Loan                  `protobuf:"bytes,1,opt,name=loan,proto3" json:"loan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLoanRequest) Reset() {
	*x = UpdateLoanRequest{}
	mi := &file_loan_loan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLoanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLoanRequest) ProtoMessage() {}

func (x *UpdateLoanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_loan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLoanRequest.ProtoReflect.Descriptor instead.
func (*UpdateLoanRequest) Descriptor() ([]byte, []int) {
	return file_loan_loan_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLoanRequest) GetLoan() *Loan {
	if x != nil {
		return x.Loan
	}
	return nil
}

// Response when a loan is updated
type UpdateLoanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLoanResponse) Reset() {
	*x = UpdateLoanResponse{}
	mi := &file_loan_loan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLoanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLoanResponse) ProtoMessage() {}

func (x *UpdateLoanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_loan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLoanResponse.ProtoReflect.Descriptor instead.
func (*UpdateLoanResponse) Descriptor() ([]byte, []int) {
	return file_loan_loan_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateLoanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request to delete a loan
type DeleteLoanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLoanRequest) Reset() {
	*x = DeleteLoanRequest{}
	mi := &file_loan_loan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLoanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLoanRequest) ProtoMessage() {}

func (x *DeleteLoanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_loan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLoanRequest.ProtoReflect.Descriptor instead.
func (*DeleteLoanRequest) Descriptor() ([]byte, []int) {
	return file_loan_loan_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteLoanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response when a loan is deleted
type DeleteLoanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLoanResponse) Reset() {
	*x = DeleteLoanResponse{}
	mi := &file_loan_loan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLoanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLoanResponse) ProtoMessage() {}

func (x *DeleteLoanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_loan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLoanResponse.ProtoReflect.Descriptor instead.
func (*DeleteLoanResponse) Descriptor() ([]byte, []int) {
	return file_loan_loan_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteLoanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request for listing loans with search, sort, and pagination
type ListLoansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchQuery   string                 `protobuf:"bytes,1,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"` // Search query to filter by book_id, member_id, etc.
	SortBy        string                 `protobuf:"bytes,2,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`                // Field to sort by (e.g., loan_date, status, etc.)
	SortOrder     string                 `protobuf:"bytes,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`       // Sort order (asc or desc)
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`                                 // Page number (for pagination)
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`         // Number of items per page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoansRequest) Reset() {
	*x = ListLoansRequest{}
	mi := &file_loan_loan_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoansRequest) ProtoMessage() {}

func (x *ListLoansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_loan_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoansRequest.ProtoReflect.Descriptor instead.
func (*ListLoansRequest) Descriptor() ([]byte, []int) {
	return file_loan_loan_proto_rawDescGZIP(), []int{9}
}

func (x *ListLoansRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *ListLoansRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListLoansRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *ListLoansRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLoansRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Response when listing loans with pagination
type ListLoansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loans         []*Loan                `protobuf:"bytes,1,rep,name=loans,proto3" json:"loans,omitempty"`                              // List of loans returned
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Total number of loans that match the query
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoansResponse) Reset() {
	*x = ListLoansResponse{}
	mi := &file_loan_loan_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoansResponse) ProtoMessage() {}

func (x *ListLoansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_loan_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoansResponse.ProtoReflect.Descriptor instead.
func (*ListLoansResponse) Descriptor() ([]byte, []int) {
	return file_loan_loan_proto_rawDescGZIP(), []int{10}
}

func (x *ListLoansResponse) GetLoans() []*Loan {
	if x != nil {
		return x.Loans
	}
	return nil
}

func (x *ListLoansResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_loan_loan_proto protoreflect.FileDescriptor

const file_loan_loan_proto_rawDesc = "" +
	"\n" +
	"\x0floan/loan.proto\x12\x04loan\"\xbd\x01\n" +
	"\x04Loan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\x12\x1b\n" +
	"\tmember_id\x18\x03 \x01(\tR\bmemberId\x12\x1b\n" +
	"\tloan_date\x18\x04 \x01(\tR\bloanDate\x12\x19\n" +
	"\bdue_date\x18\x05 \x01(\tR\adueDate\x12\x1f\n" +
	"\vreturn_date\x18\x06 \x01(\tR\n" +
	"returnDate\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"3\n" +
	"\x11CreateLoanRequest\x12\x1e\n" +
	"\x04loan\x18\x01 \x01(\v2\n" +
	".loan.LoanR\x04loan\"$\n" +
	"\x12CreateLoanResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\x0fReadLoanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x10ReadLoanResponse\x12\x1e\n" +
	"\x04loan\x18\x01 \x01(\v2\n" +
	".loan.LoanR\x04loan\"3\n" +
	"\x11UpdateLoanRequest\x12\x1e\n" +
	"\x04loan\x18\x01 \x01(\v2\n" +
	".loan.LoanR\x04loan\".\n" +
	"\x12UpdateLoanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"\x11DeleteLoanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteLoanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9e\x01\n" +
	"\x10ListLoansRequest\x12!\n" +
	"\fsearch_query\x18\x01 \x01(\tR\vsearchQuery\x12\x17\n" +
	"\asort_by\x18\x02 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\tR\tsortOrder\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"V\n" +
	"\x11ListLoansResponse\x12 \n" +
	"\x05loans\x18\x01 \x03(\v2\n" +
	".loan.LoanR\x05loans\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount2\xc9\x02\n" +
	"\vLoanService\x12?\n" +
	"\n" +
	"CreateLoan\x12\x17.loan.CreateLoanRequest\x1a\x18.loan.CreateLoanResponse\x129\n" +
	"\bReadLoan\x12\x15.loan.ReadLoanRequest\x1a\x16.loan.ReadLoanResponse\x12?\n" +
	"\n" +
	"UpdateLoan\x12\x17.loan.UpdateLoanRequest\x1a\x18.loan.UpdateLoanResponse\x12?\n" +
	"\n" +
	"DeleteLoan\x12\x17.loan.DeleteLoanRequest\x1a\x18.loan.DeleteLoanResponse\x12<\n" +
	"\tListLoans\x12\x16.loan.ListLoansRequest\x1a\x17.loan.ListLoansResponseB\tZ\a./;loanb\x06proto3"

var (
	file_loan_loan_proto_rawDescOnce sync.Once
	file_loan_loan_proto_rawDescData []byte
)

func file_loan_loan_proto_rawDescGZIP() []byte {
	file_loan_loan_proto_rawDescOnce.Do(func() {
		file_loan_loan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loan_loan_proto_rawDesc), len(file_loan_loan_proto_rawDesc)))
	})
	return file_loan_loan_proto_rawDescData
}

var file_loan_loan_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_loan_loan_proto_goTypes = []any{
	(*Loan)(nil),               // 0: loan.Loan
	(*CreateLoanRequest)(nil),  // 1: loan.CreateLoanRequest
	(*CreateLoanResponse)(nil), // 2: loan.CreateLoanResponse
	(*ReadLoanRequest)(nil),    // 3: loan.ReadLoanRequest
	(*ReadLoanResponse)(nil),   // 4: loan.ReadLoanResponse
	(*UpdateLoanRequest)(nil),  // 5: loan.UpdateLoanRequest
	(*UpdateLoanResponse)(nil), // 6: loan.UpdateLoanResponse
	(*DeleteLoanRequest)(nil),  // 7: loan.DeleteLoanRequest
	(*DeleteLoanResponse)(nil), // 8: loan.DeleteLoanResponse
	(*ListLoansRequest)(nil),   // 9: loan.ListLoansRequest
	(*ListLoansResponse)(nil),  // 10: loan.ListLoansResponse
}
var file_loan_loan_proto_depIdxs = []int32{
	0,  // 0: loan.CreateLoanRequest.loan:type_name -> loan.Loan
	0,  // 1: loan.ReadLoanResponse.loan:type_name -> loan.Loan
	0,  // 2: loan.UpdateLoanRequest.loan:type_name -> loan.Loan
	0,  // 3: loan.ListLoansResponse.loans:type_name -> loan.Loan
	1,  // 4: loan.LoanService.CreateLoan:input_type -> loan.CreateLoanRequest
	3,  // 5: loan.LoanService.ReadLoan:input_type -> loan.ReadLoanRequest
	5,  // 6: loan.LoanService.UpdateLoan:input_type -> loan.UpdateLoanRequest
	7,  // 7: loan.LoanService.DeleteLoan:input_type -> loan.DeleteLoanRequest
	9,  // 8: loan.LoanService.ListLoans:input_type -> loan.ListLoansRequest
	2,  // 9: loan.LoanService.CreateLoan:output_type -> loan.CreateLoanResponse
	4,  // 10: loan.LoanService.ReadLoan:output_type -> loan.ReadLoanResponse
	6,  // 11: loan.LoanService.UpdateLoan:output_type -> loan.UpdateLoanResponse
	8,  // 12: loan.LoanService.DeleteLoan:output_type -> loan.DeleteLoanResponse
	10, // 13: loan.LoanService.ListLoans:output_type -> loan.ListLoansResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_loan_loan_proto_init() }
func file_loan_loan_proto_init() {
	if File_loan_loan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loan_loan_proto_rawDesc), len(file_loan_loan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loan_loan_proto_goTypes,
		DependencyIndexes: file_loan_loan_proto_depIdxs,
		MessageInfos:      file_loan_loan_proto_msgTypes,
	}.Build()
	File_loan_loan_proto = out.File
	file_loan_loan_proto_goTypes = nil
	file_loan_loan_proto_depIdxs = nil
}
